# Delete file for contract building and testing. Substrate and rust versioning are out of sync. File is currently required for running a node
[toolchain]
channel = "nightly-2023-01-01"
components = [ "rustfmt" ]
targets = [ "wasm32-unknown-unknown" ]
profile = "minimal"